version: "3.9"

services:
  backend:
    build: ./chattr-backend/
    ports:
      - 9000:9000
    environment: 
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET_ACCESS=${JWT_SECRET_ACCESS}
      - JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
    depends_on:
      - mongodb
  frontend:
    build: ./chattr-frontend/
    ports:
      - 3000:3000
    environment: 
      - BACKEND_URL=${BACKEND_URL}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
  mongodb:
    image: mongo:latest
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
    volumes:
      - ~/mongodb:/data/db
    ports:
      - 27017:27017
    command: ["--auth", "--dbpath", "/data/db", "--bind_ip", "0.0.0.0"]
  nginx:
    image: nginx:latest
    ports: 
      - 80:80
      - 8080:8080
      - 443:443
    volumes: 
      - ./templates:/etc/nginx/templates
    environment: 
      - FRONTEND_HOST=${FRONTEND_HOST}
      - BACKEND_HOST=${BACKEND_HOST}
      - FRONTEND_PROXY=${FRONTEND_PROXY}
      - BACKEND_PROXY=${BACKEND_PROXY}

      - FRONTEND_CERT=${FRONTEND_CERT}
      - FRONTEND_KEY=${FRONTEND_KEY}
      - BACKEND_CERT=${BACKEND_CERT}
      - BACKEND_KEY=${BACKEND_KEY}

    command: >
      sh -c "mkdir -p /etc/nginx/ssl/${BACKEND_HOST}
      && echo '$BACKEND_CERT' > /etc/nginx/ssl/${BACKEND_HOST}/cert.pem
      && echo '$BACKEND_KEY' > /etc/nginx/ssl/${BACKEND_HOST}/private.pem
      && mkdir -p /etc/nginx/ssl/${FRONTEND_HOST}
      && echo '$FRONTEND_CERT' > /etc/nginx/ssl/${FRONTEND_HOST}/cert.pem
      && echo '$FRONTEND_KEY' > /etc/nginx/ssl/${FRONTEND_HOST}/private.pem
      && envsubst '$$FRONTEND_HOST $$BACKEND_HOST $$FRONTEND_PROXY $$BACKEND_PROXY' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;' && tail -f /dev/null"

    depends_on: 
      - frontend
      - backend


